export const regions = [
  '수원시',
  '성남시',
  '의정부시',
  '안양시',
  '부천시',
  '광명시',
  '평택시',
  '동두천시',
  '안산시',
  '고양시',
  '과천시',
  '구리시',
  '남양주시',
  '오산시',
  '시흥시',
  '군포시',
  '의왕시',
  '하남시',
  '용인시',
  '파주시',
  '이천시',
  '안성시',
  '김포시',
  '양주시',
  '포천시',
  '여주시',
  '가평군',
  '양평군',
];

export const targets = [
  '장애인',
  '저소득',
  '한부모/조손',
  '보훈대상자',
  '다문화/새터민',
  '다자녀',
];

export const regionMap: Record<string, string> = {
  수원시: 'SUWON',
  성남시: 'SEONGNAM',
  의정부시: 'UIJEONGBU',
  안양시: 'ANYANG',
  부천시: 'BUCHEON',
  광명시: 'GWANGMYEONG',
  평택시: 'PYEONGTAEK',
  동두천시: 'DONGDUCHEON',
  안산시: 'ANSAN',
  고양시: 'GOYANG',
  과천시: 'GWACHEON',
  구리시: 'GURI',
  남양주시: 'NAMYANGJU',
  오산시: 'OSAN',
  시흥시: 'SIHEUNG',
  군포시: 'GUNPO',
  의왕시: 'UIWANG',
  하남시: 'HANAM',
  용인시: 'YONGIN',
  파주시: 'PAJU',
  이천시: 'ICHEON',
  안성시: 'ANSEONG',
  김포시: 'GIMPO',
  양주시: 'YANGJU',
  포천시: 'POCHEON',
  여주시: 'YEOJU',
  가평군: 'GAPYEONG',
  양평군: 'YANGPYEONG',
};

export const targetMap: Record<string, string> = {
  장애인: 'DISABILITY',
  저소득: 'LOW_INCOME',
  '한부모/조손': 'SINGLE_PARENT_OR_GRANDPARENT',
  보훈대상자: 'VETERANS',
  '다문화/새터민': 'MIGRANT_OR_MULTICULTURAL',
  다자녀: 'MULTI_CHILD_FAMILY',
};
